language: python
python:
  - 3.3
  - 3.4
#  - pypy3
install:
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install python-coveralls
  - python setup.py install
script:
  - py.test --cov pytron tests/*
after_success:
  - coveralls
